// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: easytshark_worker.proto
#ifndef GRPC_easytshark_5fworker_2eproto__INCLUDED
#define GRPC_easytshark_5fworker_2eproto__INCLUDED

#include "easytshark_worker.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace easytshark {
namespace grpc {

class WorkerRegistry final {
 public:
  static constexpr char const* service_full_name() {
    return "easytshark.grpc.WorkerRegistry";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::easytshark::grpc::RegisterReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    virtual ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::easytshark::grpc::HeartbeatReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>> AsyncHeartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::RegisterReply>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::HeartbeatReply>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::easytshark::grpc::RegisterReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>> AsyncRegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>>(AsyncRegisterWorkerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>> PrepareAsyncRegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>>(PrepareAsyncRegisterWorkerRaw(context, request, cq));
    }
    ::grpc::Status Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::easytshark::grpc::HeartbeatReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>> AsyncHeartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>>(AsyncHeartbeatRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>> PrepareAsyncHeartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>>(PrepareAsyncHeartbeatRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, std::function<void(::grpc::Status)>) override;
      void RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, std::function<void(::grpc::Status)>) override;
      void Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>* AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>* PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>* AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>* PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterWorker_;
    const ::grpc::internal::RpcMethod rpcmethod_Heartbeat_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegisterWorker(::grpc::ServerContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response);
    virtual ::grpc::Status Heartbeat(::grpc::ServerContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::easytshark::grpc::WorkerInfo* request, ::grpc::ServerAsyncResponseWriter< ::easytshark::grpc::RegisterReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Heartbeat() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::easytshark::grpc::WorkerHeartbeat* request, ::grpc::ServerAsyncResponseWriter< ::easytshark::grpc::HeartbeatReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegisterWorker<WithAsyncMethod_Heartbeat<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response) { return this->RegisterWorker(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterWorker(
        ::grpc::MessageAllocator< ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response) { return this->Heartbeat(context, request, response); }));}
    void SetMessageAllocatorFor_Heartbeat(
        ::grpc::MessageAllocator< ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegisterWorker<WithCallbackMethod_Heartbeat<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Heartbeat() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterWorker(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHeartbeat(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterWorker(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterWorker(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Heartbeat() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Heartbeat(context, request, response); }));
    }
    ~WithRawCallbackMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Heartbeat(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterWorker : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterWorker() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply>* streamer) {
                       return this->StreamedRegisterWorker(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterWorker() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterWorker(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerInfo* /*request*/, ::easytshark::grpc::RegisterReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterWorker(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::easytshark::grpc::WorkerInfo,::easytshark::grpc::RegisterReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Heartbeat : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Heartbeat() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply>* streamer) {
                       return this->StreamedHeartbeat(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Heartbeat() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Heartbeat(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::WorkerHeartbeat* /*request*/, ::easytshark::grpc::HeartbeatReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHeartbeat(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::easytshark::grpc::WorkerHeartbeat,::easytshark::grpc::HeartbeatReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_Heartbeat<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegisterWorker<WithStreamedUnaryMethod_Heartbeat<Service > > StreamedService;
};

class PacketAnalyzeService final {
 public:
  static constexpr char const* service_full_name() {
    return "easytshark.grpc.PacketAnalyzeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::easytshark::grpc::AnalyzeBatch>> AnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::easytshark::grpc::AnalyzeBatch>>(AnalyzePacketRangeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>> AsyncAnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>>(AsyncAnalyzePacketRangeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>> PrepareAsyncAnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>>(PrepareAsyncAnalyzePacketRangeRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::easytshark::grpc::CancelReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>> AsyncCancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>>(AsyncCancelTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>> PrepareAsyncCancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>>(PrepareAsyncCancelTaskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask* request, ::grpc::ClientReadReactor< ::easytshark::grpc::AnalyzeBatch>* reactor) = 0;
      virtual void CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::easytshark::grpc::AnalyzeBatch>* AnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>* AsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::easytshark::grpc::AnalyzeBatch>* PrepareAsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>* AsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::easytshark::grpc::CancelReply>* PrepareAsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::easytshark::grpc::AnalyzeBatch>> AnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::easytshark::grpc::AnalyzeBatch>>(AnalyzePacketRangeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>> AsyncAnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>>(AsyncAnalyzePacketRangeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>> PrepareAsyncAnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>>(PrepareAsyncAnalyzePacketRangeRaw(context, request, cq));
    }
    ::grpc::Status CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::easytshark::grpc::CancelReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>> AsyncCancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>>(AsyncCancelTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>> PrepareAsyncCancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>>(PrepareAsyncCancelTaskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask* request, ::grpc::ClientReadReactor< ::easytshark::grpc::AnalyzeBatch>* reactor) override;
      void CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, std::function<void(::grpc::Status)>) override;
      void CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::easytshark::grpc::AnalyzeBatch>* AnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request) override;
    ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>* AsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>* PrepareAsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>* AsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>* PrepareAsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AnalyzePacketRange_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* context, const ::easytshark::grpc::AnalyzeTask* request, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* writer);
    virtual ::grpc::Status CancelTask(::grpc::ServerContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzePacketRange(::grpc::ServerContext* context, ::easytshark::grpc::AnalyzeTask* request, ::grpc::ServerAsyncWriter< ::easytshark::grpc::AnalyzeBatch>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelTask() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelTask(::grpc::ServerContext* context, ::easytshark::grpc::TaskId* request, ::grpc::ServerAsyncResponseWriter< ::easytshark::grpc::CancelReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AnalyzePacketRange<WithAsyncMethod_CancelTask<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::easytshark::grpc::AnalyzeTask, ::easytshark::grpc::AnalyzeBatch>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::easytshark::grpc::AnalyzeTask* request) { return this->AnalyzePacketRange(context, request); }));
    }
    ~WithCallbackMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::easytshark::grpc::AnalyzeBatch>* AnalyzePacketRange(
      ::grpc::CallbackServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CancelTask() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response) { return this->CancelTask(context, request, response); }));}
    void SetMessageAllocatorFor_CancelTask(
        ::grpc::MessageAllocator< ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelTask(
      ::grpc::CallbackServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AnalyzePacketRange<WithCallbackMethod_CancelTask<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelTask() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzePacketRange(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelTask() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->AnalyzePacketRange(context, request); }));
    }
    ~WithRawCallbackMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* AnalyzePacketRange(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CancelTask() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CancelTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelTask() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply>* streamer) {
                       return this->StreamedCancelTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelTask(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::TaskId* /*request*/, ::easytshark::grpc::CancelReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::easytshark::grpc::TaskId,::easytshark::grpc::CancelReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CancelTask<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_AnalyzePacketRange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_AnalyzePacketRange() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::easytshark::grpc::AnalyzeTask, ::easytshark::grpc::AnalyzeBatch>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::easytshark::grpc::AnalyzeTask, ::easytshark::grpc::AnalyzeBatch>* streamer) {
                       return this->StreamedAnalyzePacketRange(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_AnalyzePacketRange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AnalyzePacketRange(::grpc::ServerContext* /*context*/, const ::easytshark::grpc::AnalyzeTask* /*request*/, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedAnalyzePacketRange(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::easytshark::grpc::AnalyzeTask,::easytshark::grpc::AnalyzeBatch>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_AnalyzePacketRange<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_AnalyzePacketRange<WithStreamedUnaryMethod_CancelTask<Service > > StreamedService;
};

}  // namespace grpc
}  // namespace easytshark


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_easytshark_5fworker_2eproto__INCLUDED
