// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: easytshark_worker.proto

#include "easytshark_worker.pb.h"
#include "easytshark_worker.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace easytshark {
namespace grpc {

static const char* WorkerRegistry_method_names[] = {
  "/easytshark.grpc.WorkerRegistry/RegisterWorker",
  "/easytshark.grpc.WorkerRegistry/Heartbeat",
};

std::unique_ptr< WorkerRegistry::Stub> WorkerRegistry::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WorkerRegistry::Stub> stub(new WorkerRegistry::Stub(channel, options));
  return stub;
}

WorkerRegistry::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegisterWorker_(WorkerRegistry_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Heartbeat_(WorkerRegistry_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WorkerRegistry::Stub::RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::easytshark::grpc::RegisterReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterWorker_, context, request, response);
}

void WorkerRegistry::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, std::move(f));
}

void WorkerRegistry::Stub::async::RegisterWorker(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterWorker_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>* WorkerRegistry::Stub::PrepareAsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::easytshark::grpc::RegisterReply, ::easytshark::grpc::WorkerInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterWorker_, context, request);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::RegisterReply>* WorkerRegistry::Stub::AsyncRegisterWorkerRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterWorkerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WorkerRegistry::Stub::Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::easytshark::grpc::HeartbeatReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Heartbeat_, context, request, response);
}

void WorkerRegistry::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, std::move(f));
}

void WorkerRegistry::Stub::async::Heartbeat(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Heartbeat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>* WorkerRegistry::Stub::PrepareAsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::easytshark::grpc::HeartbeatReply, ::easytshark::grpc::WorkerHeartbeat, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Heartbeat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::HeartbeatReply>* WorkerRegistry::Stub::AsyncHeartbeatRaw(::grpc::ClientContext* context, const ::easytshark::grpc::WorkerHeartbeat& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHeartbeatRaw(context, request, cq);
  result->StartCall();
  return result;
}

WorkerRegistry::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRegistry_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRegistry::Service, ::easytshark::grpc::WorkerInfo, ::easytshark::grpc::RegisterReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRegistry::Service* service,
             ::grpc::ServerContext* ctx,
             const ::easytshark::grpc::WorkerInfo* req,
             ::easytshark::grpc::RegisterReply* resp) {
               return service->RegisterWorker(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WorkerRegistry_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WorkerRegistry::Service, ::easytshark::grpc::WorkerHeartbeat, ::easytshark::grpc::HeartbeatReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WorkerRegistry::Service* service,
             ::grpc::ServerContext* ctx,
             const ::easytshark::grpc::WorkerHeartbeat* req,
             ::easytshark::grpc::HeartbeatReply* resp) {
               return service->Heartbeat(ctx, req, resp);
             }, this)));
}

WorkerRegistry::Service::~Service() {
}

::grpc::Status WorkerRegistry::Service::RegisterWorker(::grpc::ServerContext* context, const ::easytshark::grpc::WorkerInfo* request, ::easytshark::grpc::RegisterReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WorkerRegistry::Service::Heartbeat(::grpc::ServerContext* context, const ::easytshark::grpc::WorkerHeartbeat* request, ::easytshark::grpc::HeartbeatReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* PacketAnalyzeService_method_names[] = {
  "/easytshark.grpc.PacketAnalyzeService/AnalyzePacketRange",
  "/easytshark.grpc.PacketAnalyzeService/CancelTask",
};

std::unique_ptr< PacketAnalyzeService::Stub> PacketAnalyzeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PacketAnalyzeService::Stub> stub(new PacketAnalyzeService::Stub(channel, options));
  return stub;
}

PacketAnalyzeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AnalyzePacketRange_(PacketAnalyzeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_CancelTask_(PacketAnalyzeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::easytshark::grpc::AnalyzeBatch>* PacketAnalyzeService::Stub::AnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request) {
  return ::grpc::internal::ClientReaderFactory< ::easytshark::grpc::AnalyzeBatch>::Create(channel_.get(), rpcmethod_AnalyzePacketRange_, context, request);
}

void PacketAnalyzeService::Stub::async::AnalyzePacketRange(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask* request, ::grpc::ClientReadReactor< ::easytshark::grpc::AnalyzeBatch>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::easytshark::grpc::AnalyzeBatch>::Create(stub_->channel_.get(), stub_->rpcmethod_AnalyzePacketRange_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>* PacketAnalyzeService::Stub::AsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::easytshark::grpc::AnalyzeBatch>::Create(channel_.get(), cq, rpcmethod_AnalyzePacketRange_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::easytshark::grpc::AnalyzeBatch>* PacketAnalyzeService::Stub::PrepareAsyncAnalyzePacketRangeRaw(::grpc::ClientContext* context, const ::easytshark::grpc::AnalyzeTask& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::easytshark::grpc::AnalyzeBatch>::Create(channel_.get(), cq, rpcmethod_AnalyzePacketRange_, context, request, false, nullptr);
}

::grpc::Status PacketAnalyzeService::Stub::CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::easytshark::grpc::CancelReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CancelTask_, context, request, response);
}

void PacketAnalyzeService::Stub::async::CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelTask_, context, request, response, std::move(f));
}

void PacketAnalyzeService::Stub::async::CancelTask(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CancelTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>* PacketAnalyzeService::Stub::PrepareAsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::easytshark::grpc::CancelReply, ::easytshark::grpc::TaskId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CancelTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::easytshark::grpc::CancelReply>* PacketAnalyzeService::Stub::AsyncCancelTaskRaw(::grpc::ClientContext* context, const ::easytshark::grpc::TaskId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCancelTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

PacketAnalyzeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketAnalyzeService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PacketAnalyzeService::Service, ::easytshark::grpc::AnalyzeTask, ::easytshark::grpc::AnalyzeBatch>(
          [](PacketAnalyzeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::easytshark::grpc::AnalyzeTask* req,
             ::grpc::ServerWriter<::easytshark::grpc::AnalyzeBatch>* writer) {
               return service->AnalyzePacketRange(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketAnalyzeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PacketAnalyzeService::Service, ::easytshark::grpc::TaskId, ::easytshark::grpc::CancelReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PacketAnalyzeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::easytshark::grpc::TaskId* req,
             ::easytshark::grpc::CancelReply* resp) {
               return service->CancelTask(ctx, req, resp);
             }, this)));
}

PacketAnalyzeService::Service::~Service() {
}

::grpc::Status PacketAnalyzeService::Service::AnalyzePacketRange(::grpc::ServerContext* context, const ::easytshark::grpc::AnalyzeTask* request, ::grpc::ServerWriter< ::easytshark::grpc::AnalyzeBatch>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PacketAnalyzeService::Service::CancelTask(::grpc::ServerContext* context, const ::easytshark::grpc::TaskId* request, ::easytshark::grpc::CancelReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace easytshark
}  // namespace grpc
#include <grpcpp/ports_undef.inc>

